### ISSUE TITLE
Token help

### ISSUE THREAD

**Issue by Y8rz8** [hjuhlin/homebridge-aqua-temp#1]
Hi there,
I’m looking for this since many months - thanks :)
But stuck with the token part. Could you please explain how to to get the token ?
Thx,
Patrice.

**Comment by hjuhlin** [comment]
Hallo. Nice to hear that I can make someone happy :) 

But need to make you temporary sad. I did plan to make a guide to get the Token. But as I learned that it changes every day, I plan to add more code so you dont need to get it. But have not had time to fix that yet. But I need this to be fixed for my own pool, so soon! :)

**Comment by Y8rz8** [comment]
Hi ! Not so sad don’t worry ;) ok thanks ! Happy to test if you need someone !

**Comment by Y8rz8** [comment]
Hallo !
It’s seems to work :-)

**Comment by hjuhlin** [comment]
Yes it does, it was very easy to fix! But I did not tell you about it, because I did not have time to build a function that gets a new Token. It only last for max 24 hours. So it will stop working soon. Restart of Homebridge every 24 hours does the trick right now. 

But going to fix it soon, so it's gets a new ID by it self when it runs out.

**Comment by Y8rz8** [comment]
Ok clear !

**Comment by hjuhlin** [comment]
@Y8rz8 I have done a first test now with auto refreshing the token. I have just intsalled it my own live homebrige, so will let it run on my installation for a few days to test it out. 

One important thing with this new version is that you should unistall the old one before installing this. To big changes in the code.

**Comment by Y8rz8** [comment]
Just installed and it works perfectly. I will inform you in case of issues.
Thanks for your work :)

**Comment by hjuhlin** [comment]
I think all tokens problems is 100% solved now and works perfectly for me. So closing this issue.
