### ISSUE TITLE
Some Modes do not work anymore

### ISSUE THREAD

**Issue by emcepe** [hjuhlin/homebridge-aqua-temp#10]
I don't know since when because I only use silent mode on/off and off mode, but now it's so hot that I want to set cool or auto mode, but that's not working any longer (don't know if it ever worked - never tested)

The plug-in does not recognize all the modes either, it's always at heat even if it's set to cool or auto. Only off is recognized correctly.

Bug? Maybe the company changed something in the API?

**Comment by hjuhlin** [comment]
The only mode that's supported is in API is off and heat.
