### ISSUE TITLE
[Aqua Temp] Found 0 device

### ISSUE THREAD

**Issue by bacanol** [hjuhlin/homebridge-aqua-temp#13]
**Describe Your Problem:**
The plugin installed fine and gets a token from the service. But then this log line is shown:

**Logs:**

```
[Aqua Temp] Found 0 device
```

**Plugin Config:**

```json
{
    "name": "Aqua Temp",
    "UserName": "IZIZIZ",
    "Password": "ZIZIZI",
    "UpdateTime": 60,
    "ViewWaterThermometer": true,
    "ViewElectricPowerUsage": false,
    "PowerConsumptionLimit": 0,
    "Debug": true,
    "ClearAllAtStartUp": true,
    "EveLoging": true,
    "_bridge": {
        "username": "0E:1F:13:??:??:??",
        "port": 56209
    },
    "platform": "AquaTemp"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: homebridge-aqua-temp v2.5.1
* **Homebridge Version**: v1.6.1
* **Node.js Version**: [v18.16.0]
* **NPM Version**: ?
* **Operating System**: Debian

**Comment by Sunnylaila** [comment]
Hallo, ich habe genau die gleiche Konstellation mit dem gleichen Fehler
Vielleicht kann ja hier jemand helfen.

**Comment by hjuhlin** [comment]
Hallo there! While updating to a new api code (one year after you question) I found that if you have the heater in a shared its not found. This is now fixed. So closing this :)
