### ISSUE TITLE
Plugin crashes at launch: "TypeError: Cannot read properties of undefined (reading 'x-token')"

### ISSUE THREAD

**Issue by rdouma** [hjuhlin/homebridge-aqua-temp#14]
**Describe Your Problem:**
The plugin fails to launch. I don't know what else to say; have not seen it working yet. Tried with and without child bridge, effect is the same.

**Logs:**

```
[12/29/2023, 3:10:25 AM] [Termas de Alkimia] Initializing AquaTemp platform...
[12/29/2023, 3:10:25 AM] [Termas de Alkimia] Initializing child bridge 0E:7B:A8:AE:4F:24
[12/29/2023, 3:10:25 AM] Loading 13 accessories...
[12/29/2023, 3:10:26 AM] [Termas de Alkimia] Launched child bridge with PID 38038
[12/29/2023, 3:10:26 AM] [Termas de Alkimia] Loaded homebridge-aqua-temp v2.5.1 child bridge successfully
[12/29/2023, 3:10:28 AM] [Termas de Alkimia] Child bridge process ended
[12/29/2023, 3:10:28 AM] [Termas de Alkimia] Process Ended. Code: 1, Signal: null
[12/29/2023, 3:10:35 AM] [Termas de Alkimia] Restarting Process...
[12/29/2023, 3:10:36 AM] [Termas de Alkimia] Launched child bridge with PID 38065
[12/29/2023, 3:10:38 AM] [Termas de Alkimia] Loaded homebridge-aqua-temp v2.5.1 child bridge successfully
[12/29/2023, 3:10:38 AM] Homebridge v1.7.0 (HAP v0.11.1) (Termas de Alkimia) is running on port 59950.
[12/29/2023, 3:10:38 AM] [Termas de Alkimia] Child bridge process ended
[12/29/2023, 3:10:38 AM] [Termas de Alkimia] Process Ended. Code: 1, Signal: null
[12/29/2023, 3:10:46 AM] [Termas de Alkimia] Restarting Process...
[12/29/2023, 3:10:47 AM] [Termas de Alkimia] Launched child bridge with PID 38103
[12/29/2023, 3:10:47 AM] Registering platform 'homebridge-aqua-temp.AquaTemp'
[12/29/2023, 3:10:47 AM] [Termas de Alkimia] Loaded homebridge-aqua-temp v2.5.1 child bridge successfully
[12/29/2023, 3:10:47 AM] Homebridge v1.7.0 (HAP v0.11.1) (Termas de Alkimia) is running on port 59950.
TypeError: Cannot read properties of undefined (reading 'x-token')
    at /usr/local/lib/node_modules/homebridge-aqua-temp/src/platform.ts:308:64
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[12/29/2023, 3:10:48 AM] [Termas de Alkimia] Child bridge process ended
[12/29/2023, 3:10:48 AM] [Termas de Alkimia] Process Ended. Code: 1, Signal: null
[12/29/2023, 3:10:54 AM] [Termas de Alkimia] Stopping child bridge (will not restart)...

```

**Plugin Config:**

```json
{
	"name": "Termas de Alkimia",
	"UserName": "***********",
	"Password": "***********",
	"UpdateTime": 60,
	"ViewWaterThermometer": false,
	"ViewElectricPowerUsage": true,
	"PowerConsumptionLimit": 0,
	"Debug": true,
	"ClearAllAtStartUp": false,
	"EveLoging": true,
	"_bridge": {
		"username": "0E:7B:A8:**:**:**",
		"port": 59950
	},
	"platform": "AquaTemp"
}
```

**Screenshots:**

**Environment:**

* **Plugin Version**: 2.5.1
* **Homebridge Version**: v1.7.0
* **Node.js Version**: v20.10.0
* **NPM Version**: 10.2.3
* **Operating System**: macOS Sonoma 14.2.1

**Comment by rdouma** [comment]
As an afterthought, I find it intriguing that line 64 is empty in the code: https://github.com/hjuhlin/homebridge-aqua-temp/blob/1e85f8a22b8accf167a599323b67c553b87bfeeb/src/platform.ts#L64

**Comment by loceee** [comment]
Me too. :( 

Environment:

Plugin Version: 2.5.1
Homebridge Version: v1.8.0
Node.js Version: v18.19.0

**Comment by loceee** [comment]
Ok - I have done a MITM on the app found a few things may have changed. I may attempt to fork but I don't know what I am doing with homebridge plugins.

Traffic is now https on port 449:

Password is no longer in plaintext- but is an MD5 hash.

Current:

```
  readonly urlLogin = 'http://cloud.linked-go.com:84/cloudservice/api/app/user/login.json';
  readonly urlDevicesList = 'http://cloud.linked-go.com:84/cloudservice/api/app/device/deviceList.json';
  readonly urlDevicesData = 'http://cloud.linked-go.com:84/cloudservice/api/app/device/getDataByCode.json';
  readonly urlUpdateDevice = 'http://cloud.linked-go.com:84/cloudservice/api/app/device/control.json';
```

New:

```
  readonly urlLogin = 'https://cloud.linked-go.com:449/crmservice/api/app/user/login';
  readonly urlDevicesList = 'https://cloud.linked-go.com:449/crmservice/api/app/device/deviceList';
  readonly urlDevicesData = 'https://cloud.linked-go.com:449/crmservice/api/app/device/getDataByCode';
  readonly urlUpdateDevice = 'https://cloud.linked-go.com:449/crmservice/api/app/device/control';
```

There is also the ability to share devices to another account - in my testing I tried this so I didn't get booted out of the app by authing with the same credentials in the auth request. That might be useful to implement.

https://cloud.linked-go.com:449/crmservice/api/app/device/getMyAppectDeviceShareDataList

My rudimentary look at the code looks like updating these URLs and adding some code to hash the password could resolve connectivity.

**Comment by hjuhlin** [comment]
Sorry that I forgot to answer this before. My pool heater have be closed of for the winter. Still to cold to open the pool. So I haven't not been able to check this errors my self. But huge thanks for Loceee. Will check this very soon. Normal opening time for our pool is at end if april. But the spring is a bit slow this year.

**Comment by loceee** [comment]
Thanks so much, really appreciate your efforts on this!  We will wait patiently. :) 

I think quite a few heat pumps use this rather ordinary platform (I guess at least traffic is now HTTPS!). Mine was branded with "HandyHeatpump" but the backend is identical to the AquaTemp app. I might be able to give you access to mine if that helps. I took a pass at editing forking the plugin, but didn't really know what I was doing. I might revisit later when I have time.

**Comment by stuntman76** [comment]
Me too, same problem after trying to move from hoobs to homebridge!
Logging says: 

Homebridge v1.8.2 (HAP v0.12.1) (Aqua Temp) is running on port 46813.
TypeError: Cannot read properties of undefined (reading 'x-token')
    at /homebridge/node_modules/homebridge-aqua-temp/src/platform.ts:308:64
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

Hoobs-Configuration (where it works without any problems):

Plugin Version: 2.5.1
Homebridge Version: v1.7.0
Node.js Version: v18.17.1

Homebridge-Configuration (where it doas not work with the above error-log):

Plugin Version: 2.5.1
Homebridge Version: v1.8.2
Node.js Version: v20.14.0

Identical configuration on both systems:
{
    "name": "Aqua Temp",
    "UserName": "xxxx@xxxxxxx.de",
    "Password": "xxxxxxxxx",
    "UpdateTime": 60,
    "ViewWaterThermometer": false,
    "ViewElectricPowerUsage": false,
    "PowerConsumptionLimit": 0,
    "Debug": false,
    "ClearAllAtStartUp": false,
    "EveLoging": false,
    "platform": "AquaTemp",
    "_bridge": {
        "username": "xx:xx:xx:xx:xx:xx",
        "port": xxxxx
    }
}

Any further informations needed to sort out the problem?

**Comment by loceee** [comment]
Interesting it works for you in hoobs, I thought it looked like a change to the backend was responsible for this problem - I'd assumed they'd shut down all the http endpoints.

**Comment by hjuhlin** [comment]
This should be fixed now. Can I few test 2.6 version? 
Sorry that it did take so long... :(

**Comment by stuntman76** [comment]
Now, it works again! Thank you!

**Comment by hjuhlin** [comment]
> Now, it works again! Thank you!

That is great news! :)

**Comment by loceee** [comment]
Yeah awesome! Working on mine too - just in time for me to turn my pool back on down under! Thanks so much for your great work and support 🍻
