### ISSUE TITLE
API reporting "Please Login Again" in homebridge logs

### ISSUE THREAD

**Issue by loceee** [hjuhlin/homebridge-aqua-temp#17]
I noticed some entries in the logs:

```
[02/08/2024, 07:58:51] [Aqua Temp] GetDeviceStatus Error
[02/08/2024, 07:58:51] [Aqua Temp] 请重新登录
[02/08/2024, 07:58:51] [Aqua Temp] -100
[02/08/2024, 07:58:51] [Aqua Temp] 
```

请重新登录 --> Please log in again

Restarting homebridge seems to have refreshed the token and things are ok - but perhaps it need to handle an expired auth token.

**Comment by davidapersson** [comment]
> I noticed some entries in the logs:
> 
> ```
> [02/08/2024, 07:58:51] [Aqua Temp] GetDeviceStatus Error
> [02/08/2024, 07:58:51] [Aqua Temp] 请重新登录
> [02/08/2024, 07:58:51] [Aqua Temp] -100
> [02/08/2024, 07:58:51] [Aqua Temp] 
> ```
> 
> 请重新登录 --> Please log in again
> 
> Restarting homebridge seems to have refreshed the token and things are ok - but perhaps it need to handle an expired auth token.


Issue is that you cannot use the same credentials in the App and in the Plugin since login will expire the other “device” token.

So login with App will expire the Homebridge Token and vice versa

**Comment by loceee** [comment]
Yeah I was aware of that are I am using a seperate login for the app and the plugin, and utilising the "share device" feature to the other account. I will see if the problem re-occurs as it's been ok after restarting homebridge.

**Comment by hjuhlin** [comment]
In version 2.9, the code tries to retrieve a new token if the token expires, which it has done for me several times a week. 

It also makes it possible to use the same account for the app and Homebridge, but they will log each other out, so not recommended if you also want to use the app more than occasionally.

**Comment by loceee** [comment]
Awesome! Thanks again. If you are ever in Australia pop in for a swim. :)
