### ISSUE TITLE
Siri tells me the set temperature and not the actual temperatur

### ISSUE THREAD

**Issue by kungktd** [hjuhlin/homebridge-aqua-temp#3]
First I want to say I really like and enjoy the plugin. Great work!

When asking Siri what the pool (my HomeKit name for the device) temp is, she reply with the set temperature and not the actual temperatur. Am I doing something wrong or can it be change so that Siri reports back the actual temperatur when asking "Siri, what is the pool temperature"?

**Comment by hjuhlin** [comment]
Glad that you like my plugin! :) 
`
Hmmmm... when I ask Siri what the temperature is in the pool (also my homekit name), she answers, "Pool is heating you home from X to Y. 

So I get both the current temp and the target them (would be nice with only current, but dont think thats possible if its a thermostat device). 

So are you sure you only get the target and not both?

**Comment by kungktd** [comment]
For me, Siri only tells me the set temperature.
https://youtu.be/pkLpcLitktk

**Comment by hjuhlin** [comment]
It fells like Siri is behaving a bit different. Right now, she says the current temp for me and not that heating is happening. But normal she says, Pool is heating from 28 to 30 degrees. Kind of annoying she tells it different. Also, when asking about the pool temp, I am NOT interested in the target temp. My plan is to add an option, when checked, it adds the current water temperature as a normal thermometer. Then you can ask like, what is the current pool water temperature, and it should work. 

Does that sound like a good solution?

**Comment by kungktd** [comment]
I would like that a lot. Same as you, I don’t care about the target temperature. It’s always set to 28 so only the current temperature is interesting to me. :)

**Comment by hjuhlin** [comment]
In version 1.8 there is not a setting to view one an extra thermometer for water. 
It is also affected by my start up bug: https://github.com/hjuhlin/homebridge-aqua-temp/issues/2
So, you need to restart Homebridge two times after activating the setting.

Tell me if this works for you :)
