### ISSUE TITLE
Eve logging

### ISSUE THREAD

**Issue by kungktd** [hjuhlin/homebridge-aqua-temp#5]
I just updated the plug-in and turned on Eve logging. The log throws this error though,
`[homebridge-aqua-temp] This plugin threw an error from the characteristic 'S2R2': Unhandled error thrown inside read handler for characteristic: This callback function has already been called by someone else; it can only be called one time.. See https://git.io/JtMGR for more info. `

**Comment by hjuhlin** [comment]
@kungktd thanks for testing it. I have the same problem and did find a way yesterday to fix that problem. Will keep checking in the weekend.

**Comment by hjuhlin** [comment]
This one is finnaly sorted! Damn it was hard / me beeing stupied... :P 
But now with version 1.7.0 it doesnt cause this error and it updates very fast in Eve app like it should work!
