### ISSUE TITLE
Write the temp value to an additional device?

### ISSUE THREAD

**Issue by kungktd** [hjuhlin/homebridge-aqua-temp#6]
Do you think it could be possible to update an other device whit the temperature value? Ex. when reading the temperature also write the value to “Virtual Temp Sensor”?
I would like to have the temperature included to my smart home controller (Hubitat) but the HomeKit integration is only from devices specified from Hubitat. I have created a virtual temperature sensor and exposed that sensor to HomeBridge but I haven’t found a way to mirror the Aqua temp to the virtual sensor.

**Comment by hjuhlin** [comment]
Sorry that I did forget to answer you on this one but did get stuck in the damn Eve problem. 
I did a lot of research for this suggestion, but I did not find any way to solve this in Homebridge / Homekit. Homebridge plugin can NOT write to other sensors / plugins, only the own once.  

I also did check if it would be easy for you to make a Hubitat plugin (with my guidance), but I did not understand how to get started with Hubitat. 

I did find a way from Hubitat to talk to Homebridge, but not for Hubitat to read from Homebridge. Looked like Homebridge do not have any API or so to read from. 

Mabye have an option for Homebridge aqua temp plugin to write the current temp to a file, if you can make Hubitat read that file in any sort of way? But other then that, I think it’s not possible at all.

**Comment by kungktd** [comment]
Thank you for looking into this. I have seen other requests within the Hubitat community to read status of HomeKit devices. Maybe someone will come up with a good way to do it. Until then, I’m really happy with the plugin you have made for Homebridge.
