### ISSUE TITLE
Possibility to set quiet mode

### ISSUE THREAD

**Issue by emcepe** [hjuhlin/homebridge-aqua-temp#7]
Hello.

I like to see a possibility to change the water pump to low noise mode so that one can automatically, for example, set it if photovoltaic system is not producing enough power, or if no one is at home it can be set to high speed and if someone is back home again it automatically sets back to low noise mode.

possible? :)

thank you!

**Comment by emcepe** [comment]
Any news on this?

**Comment by hjuhlin** [comment]
Hello! Sorry for not writing back to you. I have been very busy at work so I have not had a chance to add a switch for low noise mode. And Im still have much to do for some weeks. But should be easy to add a switch for that I think.

**Comment by emcepe** [comment]
Thank you for your reply.

That's ok, for this year the pool season is over because it's too cold :-(

If you could add that feature until next next spring ... :-)

**Comment by hjuhlin** [comment]
I refuse to accept that it is too cold! But I guess I will have to turn off the pool soon, especially with the crazy electricity prices we have in Sweden right now :(

But yes, until spring it should be possible to fix it! :)

**Comment by emcepe** [comment]
Right now we have 8 degree in Germany, North-Rhine Westfalia

How much do you pay for a kWh?

**Comment by hjuhlin** [comment]
> Right now we have 8 degree in Germany, North-Rhine Westfalia
> 
> How much do you pay for a kWh?

This show now be fixed! Looks like this working, but we have to test it more next summer. Going to drain the pool of water now when Im done with this task :) 

Prices goes way up and down, today around 0.2 euro / kWh. So would cost around 10 euro a day to try to keep the pool warm. But temperature is minus in the nights now.. so not even possible to keep it warm even if it heater runs all day.

**Comment by emcepe** [comment]
Ok that's pretty cheap. We have to pay 0.32 € / kWh and it's going up, like gas and diesel and so on. You may have heard about it in the news. Germany is at 1st place now for energy costs in Europe and for almost everything else one of the last places in Europe :-(((

**Comment by emcepe** [comment]
Thank you so much for silent Mode support, but one question: how do you/I set that? :)

**Comment by hjuhlin** [comment]
> Thank you so much for silent Mode support, but one question: how do you/I set that? :)

A switch under the heater setting. 
![E0A507B9-867F-40FF-85AD-E0A0CFE68F40](https://user-images.githubusercontent.com/6752136/137702076-b6685e18-8793-453b-8a1f-f34c7f8a797a.png)
